# Cloudflare account ID
name = "cloudflare-worker-template-test"
compatibility_date = "2024-11-11"
compatibility_flags = ["nodejs_compat", "nodejs_als"]
pages_build_output_dir = ".vercel/output/static"

# D1 database binding
[[d1_databases]]
binding = "cloudflare_worker_template_test"
database_name = "cloudflare-worker-template-test"
database_id = "7bbad8e3-48d1-4c8b-b20b-3c1589074d0e"
migrations_dir = "migrations"

# R2 bucket binding
[[r2_buckets]]
binding = "BUCKET"
bucket_name = "cloudflare-worker-template-test"

# KV namespace
[[kv_namespaces]]
binding = "KV"
id = "2fc6fb03867d45d6b2f1fc8e93f0e613"

# Environment variables
[vars]
ENVIRONMENT = "test"
ANALYTICS_SINK = "kv"
# Configure NEXTAUTH_SECRET via `wrangler secret put NEXTAUTH_SECRET` to keep secrets out of source control
# Configure STRIPE_SECRET_KEY via `wrangler secret put STRIPE_SECRET_KEY`
# Configure STRIPE_WEBHOOK_SECRET via `wrangler secret put STRIPE_WEBHOOK_SECRET`
